In [68]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [45]:
df = pd.read_csv("datasets/GenZ_DatingApp_Data.csv")

In [46]:
df.shape

(500, 16)

In [47]:
df.head(10)

,User_ID,Age,Gender,Location,Education,Occupation,Primary_App,Secondary_Apps,Usage_Frequency,Daily_Usage_Time,Reason_for_Using,Satisfaction,Challenges,Desired_Features,Preferred_Communication,Partner_Priorities
0,1,20,Non-binary,Bangalore,Undergraduate,Freelancer,Hinge,Hinge,Monthly,1 hour,Finding a Partner,4,Safety Concerns,Audio Calls,Video Calls,Values > Personality > Appearance
1,2,24,Female,Delhi,Undergraduate,Part-time Job,Hinge,OkCupid,Weekly,30 minutes,Casual Dating,5,Time-Wasting,Video Calls,Text,Values > Personality > Appearance
2,3,24,Non-binary,Kolkata,Undergraduate,Intern,NaN,NaN,Weekly,2 hours,Casual Dating,4,Safety Concerns,Detailed Profiles,Text,Values > Personality > Appearance
3,4,22,Non-binary,Delhi,Graduate,Full-time Job,NaN,OkCupid,Daily,30 minutes,Casual Fun,3,NaN,AI Recommendations,Voice Notes,Personality > Interests > Values
4,5,18,Male,Delhi,Graduate,Intern,OkCupid,OkCupid,Weekly,2 hours,Casual Fun,4,Safety Concerns,Video Calls,Text,Appearance > Interests > Personality
5,6,23,Female,Mumbai,Undergraduate,Student,OkCupid,NaN,Daily,1.5 hours,Casual Dating,2,NaN,Audio Calls,Video Calls,Values > Personality > Appearance
6,7,22,Non-binary,Chennai,Postgraduate,Part-time Job,Tinder,Tinder,Monthly,30 minutes,Finding a Partner,4,Time-Wasting,Audio Calls,Text,Personality > Interests > Values
7,8,21,Female,Pune,Postgraduate,Freelancer,Hinge,Tinder,Weekly,1.5 hours,Finding a Partner,2,Safety Concerns,Audio Calls,Video Calls,Values > Personality > Appearance
8,9,20,Male,Pune,Postgraduate,Part-time Job,Hinge,OkCupid,Daily,2 hours,Finding a Partner,1,Lack of Genuine Matches,Audio Calls,Text,Values > Personality > Appearance
9,10,20,Non-binary,Chennai,Undergraduate,Intern,OkCupid,Bumble,Weekly,3 hours,Finding a Partner,1,Safety Concerns,Location-Based Matching,Video Calls,Values > Personality > Appearance

In [48]:
# convert string columns into numerical data columns
# Gender, Location, Education, Occupation, Primary_App, Secondary_App, Usage_Frequency, Daily_Usage_Time, Reason_for_Using, Challenges, Desired_Features, Preferred_Communication, Partner_Priorities

for i in df.keys():
    if (i not in ['User_ID']):
        print(i, set(df[i]))

Age {18, 19, 20, 21, 22, 23, 24, 25}
Gender {'Female', 'Non-binary', 'Male'}
Location {'Delhi', 'Chennai', 'Pune', 'Hyderabad', 'Mumbai', 'Bangalore', 'Kolkata'}
Education {'Postgraduate', 'Undergraduate', 'Graduate'}
Occupation {'Student', 'Full-time Job', 'Part-time Job', 'Intern', 'Freelancer'}
Primary_App {'OkCupid', 'Tinder', 'Hinge', nan, 'Bumble'}
Secondary_Apps {'OkCupid', 'Tinder', 'Hinge', nan, 'Bumble'}
Usage_Frequency {'Monthly', 'Daily', 'Weekly'}
Daily_Usage_Time {'1.5 hours', '1 hour', '30 minutes', '2 hours', '3 hours'}
Reason_for_Using {'Social Interaction', 'Casual Dating', 'Casual Fun', 'Finding a Partner'}
Satisfaction {1, 2, 3, 4, 5}
Challenges {'Time-Wasting', 'Lack of Genuine Matches', 'Safety Concerns', nan}
Desired_Features {'Audio Calls', 'Location-Based Matching', 'Video Calls', 'Detailed Profiles', 'AI Recommendations'}
Preferred_Communication {'Text', 'Video Calls', 'Voice Notes'}
Partner_Priorities {'Appearance > Interests > Personality', 'Personality > Interests > Values', 'Values > Personality > Appearance'}

In [49]:
from typing import Literal

In [50]:
# 1. Drop weak / unused columns
df = df.drop(
    columns=[
        'Desired_Features',
        'Preferred_Communication',
        'Challenges',
        'Location'
    ]
)

# 2. Fill missing Primary_App and Secondary_Apps
df['Primary_App'] = df['Primary_App'].fillna(df['Primary_App'].mode()[0])
df['Secondary_Apps'] = df['Secondary_Apps'].fillna(df['Secondary_Apps'].mode()[0])

# 3. Convert Daily_Usage_Time into minutes
usage_time_map = {
    '30 minutes': 30,
    '1 hour': 60,
    '1.5 hours': 90,
    '2 hours': 120,
    '3 hours': 180
}

df['Daily_Usage_Time'] = df['Daily_Usage_Time'].map(usage_time_map)

# 4. Convert Usage_Frequency into numeric values
# You can think of this as approximate sessions per month
frequency_map = {
    'Monthly': 1,
    'Weekly': 2,
    'Daily': 3
}

df['Usage_Frequency'] = df['Usage_Frequency'].map(frequency_map)

# 5. Education mapping
edu_map = {
    'Graduate': 0,
    'Undergraduate': 1,
    'Postgraduate': 2
}

df['Education'] = df['Education'].map(edu_map)

# 6. Ordinal encode Partner_Priorities manually
priority_map = {
    'Appearance > Interests > Personality': 0,
    'Personality > Interests > Values': 1,
    'Values > Personality > Appearance': 2
}

df['Partner_Priorities'] = df['Partner_Priorities'].map(priority_map)

# 7. One-hot encode nominal categorical columns
nominal_cols = [
    'Gender',
    'Occupation',
    'Primary_App',
    'Secondary_Apps',
    'Reason_for_Using'
]

df = pd.get_dummies(df, columns=nominal_cols, drop_first=True)

In [62]:
df.shape

(500, 22)

In [51]:
df.head()

,User_ID,Age,Education,Usage_Frequency,Daily_Usage_Time,Satisfaction,Partner_Priorities,Gender_Male,Gender_Non-binary,Occupation_Full-time Job,...,Occupation_Student,Primary_App_Hinge,Primary_App_OkCupid,Primary_App_Tinder,Secondary_Apps_Hinge,Secondary_Apps_OkCupid,Secondary_Apps_Tinder,Reason_for_Using_Casual Fun,Reason_for_Using_Finding a Partner,Reason_for_Using_Social Interaction
0,1,20,1,1,60,4,2,False,True,False,...,False,True,False,False,True,False,False,False,True,False
1,2,24,1,2,30,5,2,False,False,False,...,False,True,False,False,False,True,False,False,False,False
2,3,24,1,2,120,4,2,False,True,False,...,False,False,True,False,True,False,False,False,False,False
3,4,22,0,3,30,3,1,False,True,True,...,False,False,True,False,False,True,False,True,False,False
4,5,18,0,2,120,4,0,True,False,False,...,False,False,True,False,False,True,False,True,False,False

In [52]:
print(df.head())
print(df.dtypes)
print(df.isna().sum())

   User_ID  Age  Education  Usage_Frequency  Daily_Usage_Time  Satisfaction  \
0        1   20          1                1                60             4
1        2   24          1                2                30             5
2        3   24          1                2               120             4
3        4   22          0                3                30             3
4        5   18          0                2               120             4

   Partner_Priorities  Gender_Male  Gender_Non-binary  \
0                   2        False               True
1                   2        False              False
2                   2        False               True
3                   1        False               True
4                   0         True              False

   Occupation_Full-time Job  ...  Occupation_Student  Primary_App_Hinge  \
0                     False  ...               False               True
1                     False  ...               False               True
2                     False  ...               False              False
3                      True  ...               False              False
4                     False  ...               False              False

   Primary_App_OkCupid  Primary_App_Tinder  Secondary_Apps_Hinge  \
0                False               False                  True
1                False               False                 False
2                 True               False                  True
3                 True               False                 False
4                 True               False                 False

   Secondary_Apps_OkCupid  Secondary_Apps_Tinder  Reason_for_Using_Casual Fun  \
0                   False                  False                        False
1                    True                  False                        False
2                   False                  False                        False
3                    True                  False                         True
4                    True                  False                         True

   Reason_for_Using_Finding a Partner  Reason_for_Using_Social Interaction
0                                True                                False
1                               False                                False
2                               False                                False
3                               False                                False
4                               False                                False

[5 rows x 22 columns]
User_ID                                int64
Age                                    int64
Education                              int64
Usage_Frequency                        int64
Daily_Usage_Time                       int64
Satisfaction                           int64
Partner_Priorities                     int64
Gender_Male                             bool
Gender_Non-binary                       bool
Occupation_Full-time Job                bool
Occupation_Intern                       bool
Occupation_Part-time Job                bool
Occupation_Student                      bool
Primary_App_Hinge                       bool
Primary_App_OkCupid                     bool
Primary_App_Tinder                      bool
Secondary_Apps_Hinge                    bool
Secondary_Apps_OkCupid                  bool
Secondary_Apps_Tinder                   bool
Reason_for_Using_Casual Fun             bool
Reason_for_Using_Finding a Partner      bool
Reason_for_Using_Social Interaction     bool
dtype: object
User_ID                                0
Age                                    0
Education                              0
Usage_Frequency                        0
Daily_Usage_Time                       0
Satisfaction                           0
Partner_Priorities                     0
Gender_Male                            0
Gender_Non-binary                      0
Occupation_Full-time Job               0
Occupation_Intern                      0
Occupation_Part-time Job               0
Occupation_Student                     0
Primary_App_Hinge                      0
Primary_App_OkCupid                    0
Primary_App_Tinder                     0
Secondary_Apps_Hinge                   0
Secondary_Apps_OkCupid                 0
Secondary_Apps_Tinder                  0
Reason_for_Using_Casual Fun            0
Reason_for_Using_Finding a Partner     0
Reason_for_Using_Social Interaction    0
dtype: int64

In [53]:
X = df.drop(columns=['Satisfaction'])
y = df['Satisfaction']

y = y - 1

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from xgboost import XGBClassifier

In [55]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

## Using XGBoost Classifier

In [56]:
model = XGBClassifier(
    objective='multi:softmax',
    num_class=5,
    n_estimators=200,
    max_depth=3,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='mlogloss',
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.23
              precision    recall  f1-score   support

           0       0.27      0.35      0.31        26
           1       0.21      0.29      0.24        17
           2       0.00      0.00      0.00        17
           3       0.17      0.15      0.16        20
           4       0.38      0.30      0.33        20

    accuracy                           0.23       100
   macro avg       0.20      0.22      0.21       100
weighted avg       0.21      0.23      0.22       100

In [60]:
actual_satisfaction = y_test + 1
predicted_satisfaction = y_pred + 1

results = pd.DataFrame({
    "Actual": actual_satisfaction,
    "Predicted": predicted_satisfaction
})

print(results.head(10))

     Actual  Predicted
361       4          2
73        4          5
374       5          5
155       3          1
104       4          3
394       2          5
377       5          2
124       3          4
68        4          4
450       2          2

## The accuracy is trash! lets use a neural network

## Using a Neural Network

In [69]:
import torch
import torch.nn as nn
import torch.optim as optim

In [120]:
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(f"Using device: {device}")

Using device: cuda

In [107]:
X = df.drop(columns=["Satisfaction"]).values
y = (df["Satisfaction"] - 1).values

In [118]:
from sklearn.preprocessing import StandardScaler

# scale the input features
# Scale input features
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [121]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

X_train = torch.tensor(X_train, dtype=torch.float32, device=device)
X_test = torch.tensor(X_test, dtype=torch.float32, device=device)

y_train = torch.tensor(y_train, dtype=torch.long, device=device)
y_test = torch.tensor(y_test, dtype=torch.long, device=device)

In [122]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([400, 21]),
 torch.Size([100, 21]),
 torch.Size([400]),
 torch.Size([100]))

In [123]:
input_size = 21
hidden_size = 64
output_size = 5

network = nn.Sequential(
    nn.Linear(input_size, hidden_size),  # Input layer
    nn.ReLU(),                           # Activation function
    nn.Linear(hidden_size, hidden_size), # Hidden layer
    nn.ReLU(),                           # Activation function
    nn.Linear(hidden_size, output_size)  # Output layer
).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(
    network.parameters(),
    lr=0.001,
    weight_decay=1e-4
)

In [133]:
def train():
    epochs = 1000

    for epoch in range(epochs):
        network.train()

        optimizer.zero_grad()

        outputs = network(X_train)
        loss = criterion(outputs, y_train)

        loss.backward()
        optimizer.step()

        if (epoch + 1) % 20 == 0:
            network.eval()

            with torch.no_grad():
                train_preds = torch.argmax(network(X_train), dim=1)
                test_preds = torch.argmax(network(X_test), dim=1)

                train_acc = (train_preds == y_train).float().mean().item()
                test_acc = (test_preds == y_test).float().mean().item()

            print()
            print(
                
                f"Epoch {epoch+1}/{epochs} | "
                f"Loss: {loss.item():.4f} | "
                f"Train Acc: {train_acc:.4f} | "
                f"Test Acc: {test_acc:.4f}"
                
            )

In [134]:
train()

Epoch 20/1000 | Loss: 0.1686 | Train Acc: 1.0000 | Test Acc: 0.2200

Epoch 40/1000 | Loss: 0.1931 | Train Acc: 1.0000 | Test Acc: 0.2200

Epoch 60/1000 | Loss: 0.1922 | Train Acc: 1.0000 | Test Acc: 0.2400

Epoch 80/1000 | Loss: 0.1688 | Train Acc: 1.0000 | Test Acc: 0.2100

Epoch 100/1000 | Loss: 0.1455 | Train Acc: 0.9975 | Test Acc: 0.2300

Epoch 120/1000 | Loss: 0.1671 | Train Acc: 1.0000 | Test Acc: 0.2000

Epoch 140/1000 | Loss: 0.1657 | Train Acc: 0.9975 | Test Acc: 0.2200

Epoch 160/1000 | Loss: 0.1313 | Train Acc: 1.0000 | Test Acc: 0.2200

Epoch 180/1000 | Loss: 0.1140 | Train Acc: 1.0000 | Test Acc: 0.2400

Epoch 200/1000 | Loss: 0.1385 | Train Acc: 1.0000 | Test Acc: 0.2600

Epoch 220/1000 | Loss: 0.2226 | Train Acc: 1.0000 | Test Acc: 0.2500

Epoch 240/1000 | Loss: 0.1756 | Train Acc: 1.0000 | Test Acc: 0.2600

Epoch 260/1000 | Loss: 0.1566 | Train Acc: 1.0000 | Test Acc: 0.2400

Epoch 280/1000 | Loss: 0.1500 | Train Acc: 1.0000 | Test Acc: 0.3400

Epoch 300/1000 | Loss: 0.1970 | Train Acc: 1.0000 | Test Acc: 0.2900

Epoch 320/1000 | Loss: 0.1208 | Train Acc: 1.0000 | Test Acc: 0.3100

Epoch 340/1000 | Loss: 0.1826 | Train Acc: 1.0000 | Test Acc: 0.2200

Epoch 360/1000 | Loss: 0.1601 | Train Acc: 0.9975 | Test Acc: 0.2000

Epoch 380/1000 | Loss: 0.2035 | Train Acc: 1.0000 | Test Acc: 0.2500

Epoch 400/1000 | Loss: 0.2110 | Train Acc: 1.0000 | Test Acc: 0.2500

Epoch 420/1000 | Loss: 0.1545 | Train Acc: 1.0000 | Test Acc: 0.2100

Epoch 440/1000 | Loss: 0.2566 | Train Acc: 1.0000 | Test Acc: 0.2300

Epoch 460/1000 | Loss: 0.1139 | Train Acc: 1.0000 | Test Acc: 0.2400

Epoch 480/1000 | Loss: 0.1322 | Train Acc: 1.0000 | Test Acc: 0.2400

Epoch 500/1000 | Loss: 0.1966 | Train Acc: 1.0000 | Test Acc: 0.2700

Epoch 520/1000 | Loss: 0.1461 | Train Acc: 1.0000 | Test Acc: 0.2000

Epoch 540/1000 | Loss: 0.2073 | Train Acc: 1.0000 | Test Acc: 0.2000

Epoch 560/1000 | Loss: 0.1895 | Train Acc: 1.0000 | Test Acc: 0.2200

Epoch 580/1000 | Loss: 0.1767 | Train Acc: 1.0000 | Test Acc: 0.2600

Epoch 600/1000 | Loss: 0.1954 | Train Acc: 0.9975 | Test Acc: 0.2600

Epoch 620/1000 | Loss: 0.1917 | Train Acc: 0.9950 | Test Acc: 0.2600

Epoch 640/1000 | Loss: 0.1943 | Train Acc: 0.9975 | Test Acc: 0.2300

Epoch 660/1000 | Loss: 0.1196 | Train Acc: 1.0000 | Test Acc: 0.2700

Epoch 680/1000 | Loss: 0.1795 | Train Acc: 1.0000 | Test Acc: 0.2400

Epoch 700/1000 | Loss: 0.1425 | Train Acc: 1.0000 | Test Acc: 0.2600

Epoch 720/1000 | Loss: 0.1364 | Train Acc: 1.0000 | Test Acc: 0.2400

Epoch 740/1000 | Loss: 0.1738 | Train Acc: 1.0000 | Test Acc: 0.2600

Epoch 760/1000 | Loss: 0.1460 | Train Acc: 1.0000 | Test Acc: 0.2300

Epoch 780/1000 | Loss: 0.2062 | Train Acc: 1.0000 | Test Acc: 0.2500

Epoch 800/1000 | Loss: 0.1526 | Train Acc: 1.0000 | Test Acc: 0.2600

Epoch 820/1000 | Loss: 0.1939 | Train Acc: 0.9950 | Test Acc: 0.2600

Epoch 840/1000 | Loss: 0.1475 | Train Acc: 1.0000 | Test Acc: 0.2600

Epoch 860/1000 | Loss: 0.1881 | Train Acc: 1.0000 | Test Acc: 0.2600

Epoch 880/1000 | Loss: 0.1430 | Train Acc: 1.0000 | Test Acc: 0.2400

Epoch 900/1000 | Loss: 0.1471 | Train Acc: 1.0000 | Test Acc: 0.2500

Epoch 920/1000 | Loss: 0.1710 | Train Acc: 1.0000 | Test Acc: 0.2600

Epoch 940/1000 | Loss: 0.1811 | Train Acc: 0.9975 | Test Acc: 0.2400

Epoch 960/1000 | Loss: 0.2685 | Train Acc: 1.0000 | Test Acc: 0.3100

Epoch 980/1000 | Loss: 0.1913 | Train Acc: 0.9975 | Test Acc: 0.2600

Epoch 1000/1000 | Loss: 0.2123 | Train Acc: 1.0000 | Test Acc: 0.3100

In [135]:
# Training accuracy is high but test accuracy is low 
# Add Dropout layers 

input_size = 21
hidden_size = 64
output_size = 5

network = nn.Sequential(
    nn.Linear(input_size, 64),
    nn.ReLU(),
    nn.Dropout(0.2),

    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Dropout(0.2),

    nn.Linear(32, output_size)
).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(
    network.parameters(),
    lr=0.05,
    weight_decay=1e-4
)

In [136]:
train()

Epoch 20/1000 | Loss: 1.0365 | Train Acc: 0.7325 | Test Acc: 0.2200

Epoch 40/1000 | Loss: 0.7658 | Train Acc: 0.8400 | Test Acc: 0.2600

Epoch 60/1000 | Loss: 0.6915 | Train Acc: 0.9300 | Test Acc: 0.2200

Epoch 80/1000 | Loss: 0.5666 | Train Acc: 0.9600 | Test Acc: 0.2000

Epoch 100/1000 | Loss: 0.4755 | Train Acc: 0.9800 | Test Acc: 0.2200

Epoch 120/1000 | Loss: 0.5426 | Train Acc: 0.9800 | Test Acc: 0.2100

Epoch 140/1000 | Loss: 0.4778 | Train Acc: 0.9900 | Test Acc: 0.2200

Epoch 160/1000 | Loss: 0.4625 | Train Acc: 0.9875 | Test Acc: 0.2200

Epoch 180/1000 | Loss: 0.5083 | Train Acc: 0.9850 | Test Acc: 0.2700

Epoch 200/1000 | Loss: 0.3919 | Train Acc: 0.9925 | Test Acc: 0.2200

Epoch 220/1000 | Loss: 0.4191 | Train Acc: 0.9925 | Test Acc: 0.2300

Epoch 240/1000 | Loss: 0.4514 | Train Acc: 0.9975 | Test Acc: 0.2200

Epoch 260/1000 | Loss: 0.3824 | Train Acc: 0.9975 | Test Acc: 0.1900

Epoch 280/1000 | Loss: 0.3978 | Train Acc: 0.9975 | Test Acc: 0.2100

Epoch 300/1000 | Loss: 0.3239 | Train Acc: 0.9975 | Test Acc: 0.2300

Epoch 320/1000 | Loss: 0.3662 | Train Acc: 0.9925 | Test Acc: 0.2300

Epoch 340/1000 | Loss: 0.3123 | Train Acc: 0.9975 | Test Acc: 0.2400

Epoch 360/1000 | Loss: 0.3547 | Train Acc: 1.0000 | Test Acc: 0.2100

Epoch 380/1000 | Loss: 0.3417 | Train Acc: 1.0000 | Test Acc: 0.2000

Epoch 400/1000 | Loss: 0.3082 | Train Acc: 1.0000 | Test Acc: 0.2400

Epoch 420/1000 | Loss: 0.1924 | Train Acc: 1.0000 | Test Acc: 0.2400

Epoch 440/1000 | Loss: 0.3374 | Train Acc: 0.9975 | Test Acc: 0.2000

Epoch 460/1000 | Loss: 0.3089 | Train Acc: 1.0000 | Test Acc: 0.2000

Epoch 480/1000 | Loss: 0.3465 | Train Acc: 1.0000 | Test Acc: 0.1700

Epoch 500/1000 | Loss: 0.3391 | Train Acc: 1.0000 | Test Acc: 0.1900

Epoch 520/1000 | Loss: 0.2723 | Train Acc: 0.9975 | Test Acc: 0.2300

Epoch 540/1000 | Loss: 0.3487 | Train Acc: 1.0000 | Test Acc: 0.2100

Epoch 560/1000 | Loss: 0.2102 | Train Acc: 1.0000 | Test Acc: 0.2200

Epoch 580/1000 | Loss: 0.2818 | Train Acc: 1.0000 | Test Acc: 0.2100

Epoch 600/1000 | Loss: 0.2450 | Train Acc: 1.0000 | Test Acc: 0.1500

Epoch 620/1000 | Loss: 0.2870 | Train Acc: 1.0000 | Test Acc: 0.1700

Epoch 640/1000 | Loss: 0.2115 | Train Acc: 1.0000 | Test Acc: 0.1900

Epoch 660/1000 | Loss: 0.2933 | Train Acc: 1.0000 | Test Acc: 0.1800

Epoch 680/1000 | Loss: 0.2648 | Train Acc: 0.9950 | Test Acc: 0.2000

Epoch 700/1000 | Loss: 0.2644 | Train Acc: 1.0000 | Test Acc: 0.1900

Epoch 720/1000 | Loss: 0.2303 | Train Acc: 1.0000 | Test Acc: 0.1900

Epoch 740/1000 | Loss: 0.2798 | Train Acc: 0.9975 | Test Acc: 0.1900

Epoch 760/1000 | Loss: 0.2747 | Train Acc: 1.0000 | Test Acc: 0.2200

Epoch 780/1000 | Loss: 0.2421 | Train Acc: 1.0000 | Test Acc: 0.1900

Epoch 800/1000 | Loss: 0.2508 | Train Acc: 1.0000 | Test Acc: 0.1700

Epoch 820/1000 | Loss: 0.3110 | Train Acc: 0.9975 | Test Acc: 0.1500

Epoch 840/1000 | Loss: 0.2404 | Train Acc: 1.0000 | Test Acc: 0.1900

Epoch 860/1000 | Loss: 0.2083 | Train Acc: 1.0000 | Test Acc: 0.2100

Epoch 880/1000 | Loss: 0.1751 | Train Acc: 0.9975 | Test Acc: 0.2000

Epoch 900/1000 | Loss: 0.2034 | Train Acc: 1.0000 | Test Acc: 0.2400

Epoch 920/1000 | Loss: 0.1709 | Train Acc: 0.9975 | Test Acc: 0.2200

Epoch 940/1000 | Loss: 0.2203 | Train Acc: 1.0000 | Test Acc: 0.2000

Epoch 960/1000 | Loss: 0.2325 | Train Acc: 0.9950 | Test Acc: 0.1600

Epoch 980/1000 | Loss: 0.1806 | Train Acc: 1.0000 | Test Acc: 0.2100

Epoch 1000/1000 | Loss: 0.1767 | Train Acc: 0.9975 | Test Acc: 0.1700